package com.privycs.vpn.data

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.core.handlers.ReplaceFileCorruptionHandler
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.emptyPreferences
import androidx.datastore.preferences.core.stringPreferencesKey
import androidx.datastore.preferences.preferencesDataStore
import com.privycs.vpn.data.models.ConnectOnDemandSettings
import com.privycs.vpn.data.models.NetworkRule
import com.privycs.vpn.data.models.RuleAction
import com.privycs.vpn.data.models.RuleMatchType
import com.privycs.vpn.data.models.RuleResolution
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.launch
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json

// Separate DataStore for network rules so they don't share the
// settings keyspace. Single-name preferencesDataStore creates the
// file lazily on first access.
private val Context.networkRulesStore: DataStore<Preferences> by preferencesDataStore(
    name = "network_rules",
    // v0.9.15.75: replace a corrupt rules file rather than throw
    // CorruptionException (loadRules() also catches — belt + braces).
    corruptionHandler = ReplaceFileCorruptionHandler { emptyPreferences() },
)

// ID prefix for rules generated by the legacy-COD → rules migration.
// Stable per-config IDs (not random UUIDs) make migrateLegacyCod
// idempotent: a re-run upserts the same rules instead of duplicating.
private const val COD_RULE_PREFIX = "cod_"

/**
 * Persists the user's network rule list. Backed by the same
 * DataStore Preferences instance as SettingsRepository (no
 * separate file for one rarely-mutated list). JSON-serialised
 * because rules are nested objects with enums.
 *
 * Rule semantics + matching are defined on NetworkRule.matches.
 * This repo just owns CRUD and ordering; the rules engine in
 * NetworkMonitor consumes the list via `resolve()`.
 *
 * Rule ordering: stored as a list, position is priority.
 * resolve() walks first-to-last; first matching rule wins.
 * Move-up/move-down operations are O(n) list mutations.
 */
class NetworkRulesRepository(private val context: Context) {

    private object Keys {
        val RULES_JSON = stringPreferencesKey("network_rules_json")
    }

    private val json = Json { ignoreUnknownKeys = true; encodeDefaults = true }
    private val serializer = ListSerializer(NetworkRule.serializer())

    // v0.9.15.74 (B-5): start empty and load asynchronously. The
    // constructor runs on the main thread (PrivycsApp.onCreate); a
    // runBlocking DataStore read at field-init stalled cold start.
    // Consumers observe `rules` / `rulesFlow`, so they pick up the
    // persisted list as soon as the async load completes.
    private val _rules = MutableStateFlow<List<NetworkRule>>(emptyList())
    val rules = _rules.asStateFlow()

    val rulesFlow: Flow<List<NetworkRule>> = _rules

    /**
     * True when the user has at least one network rule — the
     * post-COD-conversion proxy for "auto-tunnel is configured".
     */
    val hasRules: Boolean
        get() = _rules.value.isNotEmpty()

    private val loadScope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    // The initial async load, kept as a Job so callers that must read
    // the real persisted list — the COD-engine bootstrap gates and the
    // legacy-COD migration — can await it instead of racing the empty
    // start value.
    private val initialLoad: Job = loadScope.launch { _rules.value = loadRules() }

    /** Suspends until the initial async rule load has completed. */
    suspend fun awaitLoaded() {
        initialLoad.join()
    }

    private suspend fun loadRules(): List<NetworkRule> {
        return try {
            val raw = context.networkRulesStore.data.first()[Keys.RULES_JSON].orEmpty()
            if (raw.isBlank()) emptyList() else json.decodeFromString(serializer, raw)
        } catch (e: Exception) {
            android.util.Log.w("NetworkRulesRepository", "load failed: ${e.message}")
            emptyList()
        }
    }

    suspend fun save(list: List<NetworkRule>) {
        val ordered = list.mapIndexed { i, r -> r.copy(priority = i) }
        _rules.value = ordered
        val raw = json.encodeToString(serializer, ordered)
        context.networkRulesStore.edit { prefs -> prefs[Keys.RULES_JSON] = raw }
    }

    suspend fun add(rule: NetworkRule) {
        save(_rules.value + rule.copy(priority = _rules.value.size))
    }

    suspend fun update(rule: NetworkRule) {
        save(_rules.value.map { if (it.id == rule.id) rule else it })
    }

    suspend fun delete(ruleId: String) {
        save(_rules.value.filterNot { it.id == ruleId })
    }

    suspend fun reorder(orderedIds: List<String>) {
        val byId = _rules.value.associateBy { it.id }
        val ordered = orderedIds.mapNotNull { byId[it] }
        save(ordered)
    }

    /**
     * One-time conversion of the legacy "simple Connect-on-Demand"
     * (trigger + only/except SSID list) into equivalent NetworkRules.
     *
     * Runs whenever a legacy COD config is still enabled — at app
     * start AND after a backup restore — so a restored pre-conversion
     * backup is converted exactly like an in-place update.
     *
     * Idempotent: the generated rules use stable `cod_`-prefixed IDs,
     * so a re-run (e.g. process death between the rule write and the
     * settings write) upserts rather than duplicates. After a
     * successful conversion the legacy `connectOnDemand.enabled` flag
     * is cleared — that both disables the dead legacy path and stops
     * the migration re-running.
     *
     * COD-derived rules are appended AFTER any existing user rules,
     * preserving the legacy "explicit rules first, COD as fallback"
     * precedence.
     */
    suspend fun migrateLegacyCod(settingsRepo: SettingsRepository) {
        val settings = settingsRepo.getSettingsBlocking()
        val cod = settings.connectOnDemand
        if (!cod.enabled) return
        awaitLoaded()
        val generated = buildCodRules(cod)
        val kept = _rules.value.filterNot { it.id.startsWith(COD_RULE_PREFIX) }
        save(kept + generated)
        settingsRepo.updateSettings(
            settings.copy(connectOnDemand = cod.copy(enabled = false)),
        )
        android.util.Log.i(
            "NetworkRulesRepository",
            "migrated legacy COD -> ${generated.size} rule(s)",
        )
    }

    /**
     * Maps a ConnectOnDemandSettings into the equivalent ordered rule
     * list. Order matters — except-list NO_VPN rules must precede the
     * Wi-Fi catch-all so first-match-wins reproduces the legacy
     * "connect everywhere except these SSIDs" behaviour.
     */
    private fun buildCodRules(cod: ConnectOnDemandSettings): List<NetworkRule> {
        val out = mutableListOf<NetworkRule>()
        val wifi = cod.trigger == "wifi" || cod.trigger == "wifi_mobile"
        val mobile = cod.trigger == "mobile" || cod.trigger == "wifi_mobile"
        if (wifi) {
            when (cod.ssidMode) {
                "except" -> {
                    cod.ssidList.forEachIndexed { i, ssid ->
                        out += NetworkRule(
                            id = "${COD_RULE_PREFIX}ssid_$i",
                            priority = 0,
                            matchType = RuleMatchType.SSID_EXACT,
                            matchValue = ssid,
                            action = RuleAction.NO_VPN,
                        )
                    }
                    out += NetworkRule(
                        id = "${COD_RULE_PREFIX}wifi",
                        priority = 0,
                        matchType = RuleMatchType.NETWORK_TYPE,
                        matchValue = "wifi",
                        action = RuleAction.CONNECT_ACTIVE,
                    )
                }
                "only" -> {
                    cod.ssidList.forEachIndexed { i, ssid ->
                        out += NetworkRule(
                            id = "${COD_RULE_PREFIX}ssid_$i",
                            priority = 0,
                            matchType = RuleMatchType.SSID_EXACT,
                            matchValue = ssid,
                            action = RuleAction.CONNECT_ACTIVE,
                        )
                    }
                }
                else -> { // "all"
                    out += NetworkRule(
                        id = "${COD_RULE_PREFIX}wifi",
                        priority = 0,
                        matchType = RuleMatchType.NETWORK_TYPE,
                        matchValue = "wifi",
                        action = RuleAction.CONNECT_ACTIVE,
                    )
                }
            }
        }
        if (mobile) {
            out += NetworkRule(
                id = "${COD_RULE_PREFIX}mobile",
                priority = 0,
                matchType = RuleMatchType.NETWORK_TYPE,
                matchValue = "mobile",
                action = RuleAction.CONNECT_ACTIVE,
            )
        }
        return out
    }

    /**
     * Walk the rule list in priority order and return the first
     * matching rule's resolution. Empty list or no match = fall
     * through to legacy COD logic via RuleResolution.NoMatch.
     *
     * Pure logic - no side effects, no I/O. Safe to call from
     * NetworkMonitor's evaluateCurrentNetwork on every tick.
     */
    fun resolve(networkType: String, ssid: String, bssid: String): RuleResolution {
        val list = _rules.value
        if (list.isEmpty()) return RuleResolution.NoMatch
        val match = list.firstOrNull { it.matches(networkType, ssid, bssid) }
            ?: return RuleResolution.NoMatch
        return when (match.action) {
            com.privycs.vpn.data.models.RuleAction.NO_VPN -> RuleResolution.NoVpn
            com.privycs.vpn.data.models.RuleAction.POOL -> RuleResolution.Pool(match.targetId)
            com.privycs.vpn.data.models.RuleAction.CONNECTION ->
                RuleResolution.Connection(match.targetId)
            com.privycs.vpn.data.models.RuleAction.CONNECT_ACTIVE ->
                RuleResolution.ConnectActive
        }
    }
}
