// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateConnection(arg1, arg2) {
  return window['go']['main']['App']['ActivateConnection'](arg1, arg2);
}

export function CancelPause() {
  return window['go']['main']['App']['CancelPause']();
}

export function GetConnectOnDemandStatus() {
  return window['go']['main']['App']['GetConnectOnDemandStatus']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DownloadAndImportConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadAndImportConfig'](arg1, arg2, arg3, arg4);
}

export function EnsurePrivilegedHelper() {
  return window['go']['main']['App']['EnsurePrivilegedHelper']();
}

export function ExportBackup(arg1, arg2) {
  return window['go']['main']['App']['ExportBackup'](arg1, arg2);
}

export function FetchMyConfig(arg1, arg2) {
  return window['go']['main']['App']['FetchMyConfig'](arg1, arg2);
}

export function FetchMyProfile() {
  return window['go']['main']['App']['FetchMyProfile']();
}

export function GetHelperStatus() {
  return window['go']['main']['App']['GetHelperStatus']();
}

export function ImportBackup(arg1, arg2) {
  return window['go']['main']['App']['ImportBackup'](arg1, arg2);
}

export function InstallPrivilegedHelper() {
  return window['go']['main']['App']['InstallPrivilegedHelper']();
}

export function PickBackupOpenPath() {
  return window['go']['main']['App']['PickBackupOpenPath']();
}

export function PickBackupSavePath() {
  return window['go']['main']['App']['PickBackupSavePath']();
}

export function UninstallPrivilegedHelper() {
  return window['go']['main']['App']['UninstallPrivilegedHelper']();
}

export function ListPools() {
  return window['go']['main']['App']['ListPools']();
}

export function GetPoolDetail(arg1) {
  return window['go']['main']['App']['GetPoolDetail'](arg1);
}

export function CreatePoolFromPaths(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePoolFromPaths'](arg1, arg2, arg3);
}

export function UpdatePool(arg1, arg2) {
  return window['go']['main']['App']['UpdatePool'](arg1, arg2);
}

export function DeletePool(arg1) {
  return window['go']['main']['App']['DeletePool'](arg1);
}

export function DeletePoolMember(arg1, arg2) {
  return window['go']['main']['App']['DeletePoolMember'](arg1, arg2);
}

export function RenamePoolMember(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenamePoolMember'](arg1, arg2, arg3);
}

export function ActivePoolID() {
  return window['go']['main']['App']['ActivePoolID']();
}

export function ActivatePool(arg1) {
  return window['go']['main']['App']['ActivatePool'](arg1);
}

export function SwitchPoolMember(arg1) {
  return window['go']['main']['App']['SwitchPoolMember'](arg1);
}

export function PickAndConnectActivePool() {
  return window['go']['main']['App']['PickAndConnectActivePool']();
}

export function PoolRotatorStatus() {
  return window['go']['main']['App']['PoolRotatorStatus']();
}

export function SelfIPCountry() {
  return window['go']['main']['App']['SelfIPCountry']();
}

export function PauseFor(arg1) {
  return window['go']['main']['App']['PauseFor'](arg1);
}

export function SwitchActiveConnection(arg1, arg2) {
  return window['go']['main']['App']['SwitchActiveConnection'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetActiveConfigContent() {
  return window['go']['main']['App']['GetActiveConfigContent']();
}

export function GetAvailableProtocols() {
  return window['go']['main']['App']['GetAvailableProtocols']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPlatformFeatures() {
  return window['go']['main']['App']['GetPlatformFeatures']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function RemoveProtocolFromConnection(arg1, arg2) {
  return window['go']['main']['App']['RemoveProtocolFromConnection'](arg1, arg2);
}

export function RenameConnection(arg1, arg2) {
  return window['go']['main']['App']['RenameConnection'](arg1, arg2);
}

export function SaveActiveConfigContent(arg1) {
  return window['go']['main']['App']['SaveActiveConfigContent'](arg1);
}

export function SelectProtocol(arg1) {
  return window['go']['main']['App']['SelectProtocol'](arg1);
}

export function SetKillSwitch(arg1) {
  return window['go']['main']['App']['SetKillSwitch'](arg1);
}

export function SetProtocol(arg1) {
  return window['go']['main']['App']['SetProtocol'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function SwitchConnectionProtocol(arg1) {
  return window['go']['main']['App']['SwitchConnectionProtocol'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
