// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateConnection(arg1:string,arg2:string):Promise<void>;

export function CancelPause():Promise<void>;

export function Connect(arg1:string):Promise<main.StatusResponse>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetActiveConfigContent():Promise<string>;

export function GetConnectOnDemandStatus():Promise<{[key: string]: any}>;

export function ListPools():Promise<Array<{[key: string]: any}>>;

export function GetPoolDetail(arg1:string):Promise<{[key: string]: any}>;

export function CreatePoolFromPaths(arg1:string, arg2:string, arg3:Array<string>):Promise<{[key: string]: any}>;

export function UpdatePool(arg1:string, arg2:{[key: string]: any}):Promise<{[key: string]: any}>;

export function DeletePool(arg1:string):Promise<void>;

export function DeletePoolMember(arg1:string, arg2:string):Promise<void>;

export function RenamePoolMember(arg1:string, arg2:string, arg3:string):Promise<void>;

export function ActivePoolID():Promise<string>;

export function ActivatePool(arg1:string):Promise<void>;

export function SwitchPoolMember(arg1:string):Promise<void>;

export function PickAndConnectActivePool():Promise<void>;

export function PoolRotatorStatus():Promise<{[key: string]: any}>;

export function SelfIPCountry():Promise<string>;

export function GetAvailableProtocols():Promise<Array<main.ProtocolInfo>>;

export function GetLogs():Promise<Array<string>>;

export function GetPlatformFeatures():Promise<main.PlatformFeatures>;

export function GetSettings():Promise<main.AppSettings>;

export function GetVersion():Promise<string>;

export function ImportConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ListConnections():Promise<Array<main.SavedConnection>>;

export function RemoveProtocolFromConnection(arg1:string,arg2:string):Promise<void>;

export function RenameConnection(arg1:string,arg2:string):Promise<void>;

export function SaveActiveConfigContent(arg1:string):Promise<void>;

export function SelectProtocol(arg1:string):Promise<void>;

export function SetKillSwitch(arg1:boolean):Promise<void>;

export function SetProtocol(arg1:string):Promise<void>;

export function PauseFor(arg1:number):Promise<void>;

export function Status():Promise<main.StatusResponse>;

export function SwitchActiveConnection(arg1:string,arg2:string):Promise<boolean>;

export function SwitchConnectionProtocol(arg1:string):Promise<void>;

export function UpdateSettings(arg1:main.AppSettings):Promise<void>;
