// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateConnection(arg1:string,arg2:string):Promise<void>;

export function Connect(arg1:string):Promise<main.StatusResponse>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetActiveConfigContent():Promise<string>;

export function GetAvailableProtocols():Promise<Array<main.ProtocolInfo>>;

export function GetLogs():Promise<Array<string>>;

export function GetPlatformFeatures():Promise<main.PlatformFeatures>;

export function GetSettings():Promise<main.AppSettings>;

export function GetVersion():Promise<string>;

export function ImportConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ListConnections():Promise<Array<main.SavedConnection>>;

export function RemoveProtocolFromConnection(arg1:string,arg2:string):Promise<void>;

export function RenameConnection(arg1:string,arg2:string):Promise<void>;

export function SaveActiveConfigContent(arg1:string):Promise<void>;

export function SelectProtocol(arg1:string):Promise<void>;

export function SetKillSwitch(arg1:boolean):Promise<void>;

export function SetProtocol(arg1:string):Promise<void>;

export function Status():Promise<main.StatusResponse>;

export function SwitchConnectionProtocol(arg1:string):Promise<void>;

export function UpdateSettings(arg1:main.AppSettings):Promise<void>;
