// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateConnection(arg1, arg2) {
  return window['go']['main']['App']['ActivateConnection'](arg1, arg2);
}

export function CancelPause() {
  return window['go']['main']['App']['CancelPause']();
}

export function GetConnectOnDemandStatus() {
  return window['go']['main']['App']['GetConnectOnDemandStatus']();
}

export function PauseFor(arg1) {
  return window['go']['main']['App']['PauseFor'](arg1);
}

export function SwitchActiveConnection(arg1, arg2) {
  return window['go']['main']['App']['SwitchActiveConnection'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetActiveConfigContent() {
  return window['go']['main']['App']['GetActiveConfigContent']();
}

export function GetAvailableProtocols() {
  return window['go']['main']['App']['GetAvailableProtocols']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPlatformFeatures() {
  return window['go']['main']['App']['GetPlatformFeatures']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function RemoveProtocolFromConnection(arg1, arg2) {
  return window['go']['main']['App']['RemoveProtocolFromConnection'](arg1, arg2);
}

export function RenameConnection(arg1, arg2) {
  return window['go']['main']['App']['RenameConnection'](arg1, arg2);
}

export function SaveActiveConfigContent(arg1) {
  return window['go']['main']['App']['SaveActiveConfigContent'](arg1);
}

export function SelectProtocol(arg1) {
  return window['go']['main']['App']['SelectProtocol'](arg1);
}

export function SetKillSwitch(arg1) {
  return window['go']['main']['App']['SetKillSwitch'](arg1);
}

export function SetProtocol(arg1) {
  return window['go']['main']['App']['SetProtocol'](arg1);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function SwitchConnectionProtocol(arg1) {
  return window['go']['main']['App']['SwitchConnectionProtocol'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
